name: Third party libraries check

on: [ merge_group, push, pull_request ]

jobs:
  rim:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Run the third party libraries check via RIM inside the docker container
       run: DOCKER_UID=$(id -u) DOCKER_GID=$(id -g) DOCKER_HISTORY=/dev/null docker compose run --rm development rim status -d --verify-clean
